FROM python:3.7

RUN pip install torch==1.4.0+cu100 torchvision==0.5.0+cu100 -f https://download.pytorch.org/whl/torch_stable.html
RUN useradd --no-create-home --user-group mlfadmin
RUN mkdir -p /opt/mlfabrique
RUN chmod a+r,a+w,a+x /opt/mlfabrique
USER mlfadmin

WORKDIR /opt/mlfabrique
