FROM python:3.7

COPY requirements.txt /
RUN pip install -r requirements.txt
RUN useradd --no-create-home --user-group mlfadmin
RUN mkdir -p /opt/mlfabrique
RUN chmod a+r,a+w,a+x /opt/mlfabrique

WORKDIR /opt/mlfabrique
